### ISSUE TITLE
Can't see the link

### ISSUE THREAD

**Issue by dandv** [discourse/twitter-profile-link#1]
I've just [installed the plugin](https://meta.discourse.org/t/install-a-plugin/19157), logged out, and [logged back in with Twitter](http://discourse.quantifiedselfforum.com/users/qsforum/activity). Where should the link appear?

![image](https://cloud.githubusercontent.com/assets/33569/9997221/d72be2ca-603f-11e5-8d01-66026f0735f4.png)

**Comment by andypiper** [comment]
Noticing the same issue - suspect that some change in the parent CSS / JS / document has caused this to stop working.

**Comment by dandv** [comment]
The last commit fixed the issue. Thanks!
